name: Deploy to AWS EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub (optional, if pushing image)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install dependencies
        run: npm install

      - name: Set environment variables for Docker build
        run: | 
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "MQTT_BROKER_URL=${{ secrets.MQTT_BROKER_URL }}" >> .env
          echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env
          echo "MAILDEV_INCOMING_USER=${{ secrets.MAILDEV_INCOMING_USER }}" >> .env
          echo "MAILDEV_INCOMING_PASS=${{ secrets.MAILDEV_INCOMING_PASS }}" >> .env

      - name: Build Docker image
        run: docker build -t ${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }} .

      - name: Add tag docker image (optional)
        run: docker tag ${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }}_${{ github.sha }}

      - name: Push Docker image to Docker Hub (optional)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }}_${{ github.sha }}

      - name: Deploy to AWS EC2
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TAG_NAME: ${{ secrets.TAG_NAME }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          ssh -i private_key.pem -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST << 'EOF'
            # Tạo thư mục chứa container nếu chưa có
            mkdir -p /container && cd /container

            # Dừng và xóa container cũ nếu có
            if docker ps -aq --filter name=${{ secrets.IMAGE_NAME }}-production | grep -q .; then
                docker stop ${{ secrets.IMAGE_NAME }}-production || true
                docker rm -f ${{ secrets.IMAGE_NAME }}-production || true
            fi

            # Xóa image cũ nếu có
            if docker images --filter=reference=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production --quiet | grep -q .; then
                docker images --filter=reference=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production --quiet | xargs -r docker rmi -f
            fi

            # Pull image mới từ Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }}_${{ github.sha }}

            # Chạy container mới
            docker run -d -p 3001:3000 --name ${{ secrets.IMAGE_NAME }}-production ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}-production:${{ secrets.TAG_NAME }}_${{ github.sha }}
          EOF

          # Xóa private key sau khi dùng xong
          rm -f private_key.pem
